baseURL = 'https://thxdmw.github.io'
#thxdmw.github.io
languageCode = 'zh-cn'
title = '布丁'
publishDir = "docs"
# 启用主题
#theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 10000
enableGitInfo = true
timeZone = 'Asia/Shanghai'

ignoreFiles = ['\\.obsidian/*']

[params]
dark = false                             # 默认开启暗色主题
author = '布丁'
slogan = 'thx blog'
startDate = 2024                        # 'Copyright © 2016 - now'
# 激活页面加载时的过渡动画
hasActiveAnimate = true
# 激活页面浮动盒子动画
hasActiveFloatingBox = true
# 文章页是否显示其相关系列文章（页面左侧区域）
isShowRelativePosts = true
# 导航页右侧是否显示迷你必应搜索
isShowMinishipBoxOfNav = true
# 导航页是否显示顶部搜索区域
isShowShipBoxOfNav = true
# 导航页是否显示站内搜索（站内文章内容检索）
isShowLocalSearch = true
# 导航页是否显示最近文章列表
isShowRecentPostsOfNav = true

# 浏览器有缓存，更换后强制页面刷新（快捷键为 Ctrl+Shift+R）一下或重启本地服务即可，
# ------------------
hasActiveCool = true                    # 激活 cool 模式，酷爽但是消耗资源也更多，
coolBackground = 'bluesky.png'          # - coolBackground 文件位于 `/static/imgs/bg` 文件夹中，默认为 `default.jpg`
coolOpacity = 0.80                      # - coolOpacity 默认为 0.81 ，背景色彩透明度，在 0 ~ 1 之间
coolSaturate = '180%'                   # - coolSaturate 默认为 180% ，背景色彩饱和度，在 0% ~ 200% 之间
coolBlur = '6px'                        # - coolBlur 默认为 6px ，背景色彩模糊度，数值越大越模糊


# 首页图片/文字
[params.img]
# 内置默认为 `cat.svg ……`，当然你可以
# 把自己喜欢图片放在 `static/imgs/` 目录中，并在 `src` 引用它,
# ❌ 你还可以通过 `width` 调整引入图片的显示大小，
# ❌ 如果，将 `width` 设置为 '' 或 0 ，
# ❌ 将默认使用图片自身分辨率尺寸
# ❌ width = 90
# 🔔 图标用途发生变化，不再支持此处设置尺寸，但
# 新增支持设置背景色，
# 将 background 设置为 ''，默认为 `#000`
# ！ 为保证显示效果，建议选用 1：1 比例图片
#src = 'cat.svg'
src = 'buding.jpg'
background = '#0003'
# 为该图片附加一个点击链接功能，缺省为 `/about`，当然
# 你也可以定义为任何你相要的超链接
link = '/about'

[params.contact]
icp = ''                                                # 备案号，如果你不想显示，设置为 '' 空即可
icplink = ''                                            # 备案链接
beian = ''                                              # 公安备案，如果你不想显示，设置为 '' 空即可
beiancode = ''                                          # 公安备案识别码
github_user = 'thxdmw'               # Github 用户名，导航页 github 小组件使用
wechat = 'imgs/wechat.jpg'             # 微信二维码地址
github = 'https://github.com/thxdmw'
bilibili = 'https://space.bilibili.com/591540080'

[params.contact.config]
color = '#696969'                         # 图标颜色，默认为浅灰色
slogan = ''                               # 联系标语，不想显示，可以置空
# isShowNavLink = true                      # 是否在联系栏左侧显示快捷导航链接（PS：站点首页总会显示）
target = '_self'                          # 定义左侧快捷导航链接打开方式，_blank 在新标签页 _self 在当前标签页
ship = ''                                 # 联系栏 icon ，允许自定义该图标链接（/ship 为外链的个人定制化搜索页）；隐藏，设置为 '' 空即可

# 以下为 Markdown 解析擎的一些设置，
# 建议保持不变
[markup]
[markup.asciidocExt]
preserveTOC = true
[markup.highlight]
# 代码块显示风格、行号显示
style = "github"
lineNos = true
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

#[[redirects]]
#from = "/**"
#status = 404
#to = "layouts/404.html"
